// Merge split "Part 1/2/3" vocab packs back into a single deck per subject.
//
// Since new cards are now paced at 10/session by the SRS engine, pre-chopping a
// subject into ~24-card parts is redundant. This collapses every group of packs
// sharing a `parent` into one pack (id = parent, cards concatenated in part
// order) and drops the parent/parentName/part fields.
//
// It also emits src/generated/partMergeMap.ts so the client can fold saved SRS
// progress from old part ids (e.g. everyday_phrases_2) into the merged deck id.
//
// Idempotent: running again on already-merged files is a no-op.
//
//   node scripts/merge-parts.mjs

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LANG_DIR = join(ROOT, "public", "languages");
const FILES = ["main_course.json", "extension_decks.json", "grammar_decks.json"];
const UNION_KEYS = ["stories", "pictureLessons", "grammarLessons"];

const langs = readdirSync(LANG_DIR).filter((d) => statSync(join(LANG_DIR, d)).isDirectory());

/** {language: {oldPartId: mergedId}} for every id that changes. */
const mergeMap = {};

let mergedSubjects = 0;
let touchedFiles = 0;

for (const lang of langs) {
    for (const file of FILES) {
        const path = join(LANG_DIR, lang, file);
        if (!existsSync(path)) continue;

        const data = JSON.parse(readFileSync(path, "utf8"));
        const packs = data.packs ?? [];

        // Group by parent (falls back to own id), preserving first-seen order.
        const order = [];
        const groups = new Map();
        for (const p of packs) {
            const key = p.parent ?? p.id;
            if (!groups.has(key)) {
                groups.set(key, []);
                order.push(key);
            }
            groups.get(key).push(p);
        }

        let changed = false;
        const mergedPacks = order.map((key) => {
            const parts = groups.get(key).slice().sort((a, b) => (a.part ?? 1) - (b.part ?? 1));
            const base = parts[0];

            // Nothing to merge and no stale fields -> leave untouched.
            const isSplit = parts.length > 1 || base.parent !== undefined || base.part !== undefined;
            if (!isSplit) return base;
            changed = true;

            for (const p of parts) {
                if (p.id !== key) (mergeMap[lang] ??= {})[p.id] = key;
            }

            const { parent, parentName, part, cards, ...rest } = base;
            const merged = { ...rest, id: key, name: parentName ?? base.name };

            // Union list-valued resource fields across all parts (Part 1 usually
            // owns them, but be safe).
            for (const k of UNION_KEYS) {
                const seen = new Set();
                const list = [];
                for (const p of parts) for (const v of p[k] ?? []) {
                    const sig = typeof v === "object" ? JSON.stringify(v) : v;
                    if (!seen.has(sig)) { seen.add(sig); list.push(v); }
                }
                if (list.length) merged[k] = list;
            }

            merged.cards = parts.flatMap((p) => p.cards);
            mergedSubjects += parts.length > 1 ? 1 : 0;
            return merged;
        });

        if (changed) {
            writeFileSync(path, JSON.stringify({ ...data, packs: mergedPacks }, null, 2) + "\n");
            touchedFiles++;
        }
    }
}

// Emit the progress-migration map.
const genDir = join(ROOT, "src", "generated");
mkdirSync(genDir, { recursive: true });
const banner = "// AUTO-GENERATED by scripts/merge-parts.mjs — do not edit by hand.\n" +
    "// Maps old split-part deck ids to their merged subject id, per language.\n";
writeFileSync(
    join(genDir, "partMergeMap.ts"),
    banner + "export const PART_MERGE_MAP: Record<string, Record<string, string>> = " +
        JSON.stringify(mergeMap, null, 2) + ";\n"
);

console.log(`Merged ${mergedSubjects} multi-part subjects across ${touchedFiles} files.`);
console.log(`Wrote merge map for ${Object.keys(mergeMap).length} languages -> src/generated/partMergeMap.ts`);
